// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInfoRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInfoResponse {
    #[prost(string, tag = "1")]
    pub sdk_version: ::prost::alloc::string::String,
}
/// Addresses contain exactly 20 bytes; chain IDs must fit the SDK safe integer range.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WalletAccount {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub chain_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateContextRequest {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<ContextConfig>,
    #[prost(bool, tag = "2")]
    pub signer_enabled: bool,
    #[prost(message, optional, tag = "3")]
    pub account: ::core::option::Option<WalletAccount>,
    /// Omission creates isolated in-memory storage for this context.
    #[prost(message, optional, tag = "4")]
    pub storage: ::core::option::Option<StorageBinding>,
    /// Omission shares storage, including its backend identity.
    #[prost(message, optional, tag = "5")]
    pub permit_storage: ::core::option::Option<StorageBinding>,
    /// Fields 100–119 are allocated to configuration and credential protection.
    #[prost(message, optional, tag = "100")]
    pub transport_key_pair_derivation_secret: ::core::option::Option<DerivationSecret>,
}
/// Instance input for credential protection; never persisted with credentials and never logged.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DerivationSecret {
    #[prost(oneof = "derivation_secret::Value", tags = "1, 2")]
    pub value: ::core::option::Option<derivation_secret::Value>,
}
/// Nested message and enum types in `DerivationSecret`.
pub mod derivation_secret {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        Text(::prost::alloc::string::String),
        #[prost(bytes, tag = "2")]
        Bytes(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateContextResponse {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContextRequest {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAccountRequest {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub account: ::core::option::Option<WalletAccount>,
}
/// operation_id must be unique among active operations within the context.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Operation {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperationRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
}
/// encrypted_value contains a 32-byte handle; contract_address contains 20 bytes.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptedInput {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearValue {
    #[prost(oneof = "clear_value::Value", tags = "1, 2, 3, 4, 5")]
    pub value: ::core::option::Option<clear_value::Value>,
}
/// Nested message and enum types in `ClearValue`.
pub mod clear_value {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        /// Base-10 integer string for values wider than the SDK number representation.
        #[prost(string, tag = "1")]
        BigintValue(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        /// Explicit SDK undefined differs from an absent or malformed result.
        #[prost(message, tag = "4")]
        UndefinedValue(super::Empty),
        /// SDK euint8, euint16 and euint32 clear values.
        #[prost(uint32, tag = "5")]
        NumberValue(u32),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<ClearValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<EncryptedInput>,
    /// SDK relayer timeout in whole milliseconds, independent of the gRPC deadline. Omit to keep the SDK default; zero is a zero-millisecond budget, not "no timeout".
    #[prost(uint32, optional, tag = "3")]
    pub timeout_ms: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<ClearEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedDecryptValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<EncryptedInput>,
    #[prost(bytes = "vec", tag = "3")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub account_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, optional, tag = "5")]
    pub wait_for_propagation: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DecryptPublicValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub encrypted_values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// SDK relayer timeout in whole milliseconds, independent of the gRPC deadline. Omit to keep the SDK default; zero is a zero-millisecond budget, not "no timeout".
    #[prost(uint32, optional, tag = "3")]
    pub timeout_ms: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptPublicValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<ClearEntry>,
    #[prost(bytes = "vec", tag = "2")]
    pub abi_encoded_clear_values: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub decryption_proof: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedBatchDecryptValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<EncryptedInput>,
    #[prost(bytes = "vec", tag = "3")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub account_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Omission uses the SDK default; zero explicitly selects unlimited concurrency.
    #[prost(uint32, optional, tag = "5")]
    pub max_concurrency: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "6")]
    pub wait_for_propagation: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub retryable: bool,
    /// Positive whole seconds, present only for retryable errors with a valid hint.
    #[prost(uint32, optional, tag = "4")]
    pub retry_after_seconds: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchItem {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "batch_item::Result", tags = "3, 4")]
    pub result: ::core::option::Option<batch_item::Result>,
}
/// Nested message and enum types in `BatchItem`.
pub mod batch_item {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "3")]
        Value(super::ClearValue),
        #[prost(message, tag = "4")]
        Error(super::SdkError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedBatchDecryptValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<BatchItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreparePermitRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", tag = "2")]
    pub signer_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub contract_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub delegator_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Whole days; omission uses the SDK permit lifetime.
    #[prost(uint32, optional, tag = "5")]
    pub duration_days: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreparePermitResponse {
    /// Opaque SDK envelope for RegisterPermit; callers must not inspect or modify it.
    #[prost(bytes = "vec", tag = "1")]
    pub prepared_permit: ::prost::alloc::vec::Vec<u8>,
    /// EIP-712 data for application-controlled signing; dynamic types require JSON.
    #[prost(string, tag = "2")]
    pub typed_data_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPermitRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", tag = "2")]
    pub prepared_permit: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContractsRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub contract_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DelegationContractsRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", tag = "2")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub contract_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HasPermitResponse {
    #[prost(bool, tag = "1")]
    pub has_permit: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContractList {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokePermitsRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, optional, tag = "2")]
    pub contracts: ::core::option::Option<ContractList>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScopeRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(string, tag = "2")]
    pub scope_id: ::prost::alloc::string::String,
}
/// Exactly one result is required, even when the signature byte string is empty.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerReply {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(oneof = "signer_reply::Result", tags = "3, 4, 140, 141")]
    pub result: ::core::option::Option<signer_reply::Result>,
}
/// Nested message and enum types in `SignerReply`.
pub mod signer_reply {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(bytes, tag = "3")]
        Signature(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "4")]
        Error(super::SdkError),
        /// 32-byte hash of the broadcast transaction; fields 140–159 are allocated to transactions.
        #[prost(bytes, tag = "140")]
        TransactionHash(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "141")]
        ExecutionRevert(super::ExecutionRevert),
    }
}
/// The node rejected the simulated write before broadcast; nothing was sent.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecutionRevert {
    /// Raw revert return data, possibly empty; the SDK decodes it against the request ABI.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerClientMessage {
    #[prost(oneof = "signer_client_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<signer_client_message::Message>,
}
/// Nested message and enum types in `SignerClientMessage`.
pub mod signer_client_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attach(super::ContextRequest),
        #[prost(message, tag = "2")]
        Reply(super::SignerReply),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerAction {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub account: ::core::option::Option<WalletAccount>,
    /// typed_data_json keeps its original field number; the union prevents a mixed request.
    #[prost(oneof = "signer_action::Request", tags = "4, 140")]
    pub request: ::core::option::Option<signer_action::Request>,
}
/// Nested message and enum types in `SignerAction`.
pub mod signer_action {
    /// typed_data_json keeps its original field number; the union prevents a mixed request.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Request {
        #[prost(string, tag = "4")]
        TypedDataJson(::prost::alloc::string::String),
        #[prost(message, tag = "140")]
        ContractWrite(super::ContractWriteRequest),
    }
}
/// Mirrors GenericSigner.writeContract; the SDK encodes data once and native wallets broadcast it unchanged.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContractWriteRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub abi_json: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub function_name: ::prost::alloc::string::String,
    /// Bigint arguments are base-10 strings interpreted through the ABI.
    #[prost(string, tag = "5")]
    pub args_json: ::prost::alloc::string::String,
    /// Base-10 wei; omission keeps the SDK/wallet default, "0" is explicit.
    #[prost(string, optional, tag = "6")]
    pub value: ::core::option::Option<::prost::alloc::string::String>,
    /// Base-10 gas limit; omission lets the wallet estimate.
    #[prost(string, optional, tag = "7")]
    pub gas: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerReplyError {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerActionCancelled {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerServerMessage {
    #[prost(oneof = "signer_server_message::Message", tags = "1, 2, 3, 4")]
    pub message: ::core::option::Option<signer_server_message::Message>,
}
/// Nested message and enum types in `SignerServerMessage`.
pub mod signer_server_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attached(super::Empty),
        #[prost(message, tag = "2")]
        Action(super::SignerAction),
        #[prost(message, tag = "3")]
        ReplyError(super::SignerReplyError),
        #[prost(message, tag = "4")]
        Cancelled(super::SignerActionCancelled),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageBinding {
    #[prost(oneof = "storage_binding::Backend", tags = "1, 2, 3")]
    pub backend: ::core::option::Option<storage_binding::Backend>,
}
/// Nested message and enum types in `StorageBinding`.
pub mod storage_binding {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Backend {
        #[prost(message, tag = "1")]
        Memory(super::Empty),
        #[prost(string, tag = "2")]
        Persistent(::prost::alloc::string::String),
        #[prost(string, tag = "3")]
        Application(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageAction {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub backend_id: ::prost::alloc::string::String,
    #[prost(enumeration = "StorageMethod", tag = "3")]
    pub method: i32,
    #[prost(string, tag = "4")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// GET requires value or not_found; SET and DELETE require ack. Any operation may return error.
/// Empty value bytes remain distinct from not_found. Missing or mismatched results fail the operation.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageReply {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(oneof = "storage_reply::Result", tags = "2, 3, 4, 5")]
    pub result: ::core::option::Option<storage_reply::Result>,
}
/// Nested message and enum types in `StorageReply`.
pub mod storage_reply {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(bytes, tag = "2")]
        Value(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "3")]
        Error(super::SdkError),
        #[prost(message, tag = "4")]
        NotFound(super::Empty),
        #[prost(message, tag = "5")]
        Ack(super::Empty),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageClientMessage {
    #[prost(oneof = "storage_client_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<storage_client_message::Message>,
}
/// Nested message and enum types in `StorageClientMessage`.
pub mod storage_client_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attach(super::ContextRequest),
        #[prost(message, tag = "2")]
        Reply(super::StorageReply),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageReplyError {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageServerMessage {
    #[prost(oneof = "storage_server_message::Message", tags = "1, 2, 3")]
    pub message: ::core::option::Option<storage_server_message::Message>,
}
/// Nested message and enum types in `StorageServerMessage`.
pub mod storage_server_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attached(super::Empty),
        #[prost(message, tag = "2")]
        Action(super::StorageAction),
        #[prost(message, tag = "3")]
        ReplyError(super::StorageReplyError),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseContextResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAccountResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPermitResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GrantPermitResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GrantDelegationPermitResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokePermitsResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearPermitsResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarmTransportKeyPairResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarmTransportKeyPairScopeResponse {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeTransportKeyPairResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedDecryptValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<ClearEntry>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HasDelegationPermitResponse {
    #[prost(bool, tag = "1")]
    pub has_permit: bool,
}
/// Omitted credential settings retain the SDK defaults.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextConfig {
    #[prost(message, repeated, tag = "1")]
    pub chains: ::prost::alloc::vec::Vec<ChainConfig>,
    /// Omission selects the first configured chain.
    #[prost(uint64, optional, tag = "2")]
    pub chain_id: ::core::option::Option<u64>,
    /// Whole days.
    #[prost(uint32, optional, tag = "3")]
    pub permit_ttl: ::core::option::Option<u32>,
    /// Whole seconds.
    #[prost(uint32, optional, tag = "4")]
    pub transport_key_pair_ttl: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "5")]
    pub transport_key_pair_scope: ::core::option::Option<::prost::alloc::string::String>,
    /// Whole seconds.
    #[prost(uint32, optional, tag = "6")]
    pub registry_ttl: ::core::option::Option<u32>,
    /// Fields 100–119 are allocated to configuration and credential protection.
    #[prost(message, optional, tag = "100")]
    pub process_runtime: ::core::option::Option<ProcessRuntimeConfig>,
    #[prost(message, optional, tag = "101")]
    pub relayers: ::core::option::Option<RelayerMap>,
}
/// Omitted fields inherit the SDK preset for id. Custom chains supply every required field.
/// Contract addresses contain exactly 20 bytes, except explicitly cleared optional addresses.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainConfig {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, optional, tag = "2")]
    pub network: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "3")]
    pub gateway_chain_id: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "4")]
    pub relayer_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub acl_contract_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub kms_contract_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "7")]
    pub input_verifier_contract_address: ::core::option::Option<
        ::prost::alloc::vec::Vec<u8>,
    >,
    #[prost(bytes = "vec", optional, tag = "8")]
    pub verifying_contract_address_decryption: ::core::option::Option<
        ::prost::alloc::vec::Vec<u8>,
    >,
    #[prost(bytes = "vec", optional, tag = "9")]
    pub verifying_contract_address_input_verification: ::core::option::Option<
        ::prost::alloc::vec::Vec<u8>,
    >,
    /// An explicitly empty value clears the preset's optional address.
    #[prost(bytes = "vec", optional, tag = "10")]
    pub registry_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "11")]
    pub executor_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "12")]
    pub auth: ::core::option::Option<ChainAuth>,
    /// Fields 100–119 are allocated to configuration and credential protection.
    #[prost(message, optional, tag = "100")]
    pub provider: ::core::option::Option<HttpProviderConfig>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainAuth {
    #[prost(oneof = "chain_auth::Credential", tags = "1, 2, 3")]
    pub credential: ::core::option::Option<chain_auth::Credential>,
}
/// Nested message and enum types in `ChainAuth`.
pub mod chain_auth {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Credential {
        #[prost(string, tag = "1")]
        BearerToken(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        ApiKeyHeader(super::NamedCredential),
        #[prost(message, tag = "3")]
        ApiKeyCookie(super::NamedCredential),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NamedCredential {
    /// Omission preserves the SDK's default header or cookie name.
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Applied once per sidecar process; the first SDK configuration wins.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessRuntimeConfig {
    #[prost(string, optional, tag = "1")]
    pub wasm_asset_load_mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub module_versions: ::core::option::Option<ModuleVersions>,
    #[prost(bool, optional, tag = "3")]
    pub single_thread: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub number_of_threads: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "5")]
    pub auth: ::core::option::Option<ChainAuth>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleVersions {
    #[prost(oneof = "module_versions::Selection", tags = "1, 2")]
    pub selection: ::core::option::Option<module_versions::Selection>,
}
/// Nested message and enum types in `ModuleVersions`.
pub mod module_versions {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Selection {
        #[prost(message, tag = "1")]
        Auto(super::Empty),
        #[prost(message, tag = "2")]
        Pinned(super::PinnedModuleVersions),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PinnedModuleVersions {
    #[prost(string, optional, tag = "1")]
    pub tfhe: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub kms: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub check_compatibility: ::core::option::Option<::prost::alloc::string::String>,
}
/// A present empty map differs from omission: every configured chain needs a relayer.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayerMap {
    #[prost(map = "uint64, message", tag = "1")]
    pub entries: ::std::collections::HashMap<u64, RelayerConfig>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayerConfig {
    #[prost(enumeration = "RelayerTransport", tag = "1")]
    pub transport: i32,
    #[prost(message, optional, tag = "2")]
    pub options: ::core::option::Option<RelayerOptions>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RelayerOptions {
    /// Whole milliseconds.
    #[prost(uint32, optional, tag = "1")]
    pub timeout: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "2")]
    pub debug: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "3")]
    pub batch_rpc_calls: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "4")]
    pub module_versions: ::core::option::Option<ModuleVersions>,
    #[prost(message, optional, tag = "5")]
    pub fhe_encryption_key: ::core::option::Option<FheEncryptionKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FheEncryptionKey {
    #[prost(message, optional, tag = "1")]
    pub public_key_bytes: ::core::option::Option<FhePublicKeyBytes>,
    #[prost(message, optional, tag = "2")]
    pub crs_bytes: ::core::option::Option<FheCrsBytes>,
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<FheEncryptionKeyMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FhePublicKeyBytes {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub bytes: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FheCrsBytes {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub capacity: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub bytes: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FheEncryptionKeyMetadata {
    #[prost(string, tag = "1")]
    pub relayer_url: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub chain_id: u64,
}
/// Timeouts, retry delays and polling intervals are whole milliseconds.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpProviderConfig {
    #[prost(message, optional, tag = "1")]
    pub headers: ::core::option::Option<HttpHeaders>,
    #[prost(uint32, optional, tag = "2")]
    pub timeout: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub retry_count: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub retry_delay: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "5")]
    pub batch: ::core::option::Option<ProviderBatch>,
    #[prost(uint32, optional, tag = "6")]
    pub polling_interval: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpHeaders {
    #[prost(map = "string, string", tag = "1")]
    pub entries: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProviderBatch {
    #[prost(oneof = "provider_batch::Selection", tags = "1, 2")]
    pub selection: ::core::option::Option<provider_batch::Selection>,
}
/// Nested message and enum types in `ProviderBatch`.
pub mod provider_batch {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Selection {
        #[prost(bool, tag = "1")]
        Enabled(bool),
        #[prost(message, tag = "2")]
        Options(super::ProviderBatchOptions),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProviderBatchOptions {
    #[prost(uint32, optional, tag = "1")]
    pub batch_size: ::core::option::Option<u32>,
    /// Whole milliseconds.
    #[prost(uint32, optional, tag = "2")]
    pub wait: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptInput {
    #[prost(oneof = "encrypt_input::Value", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub value: ::core::option::Option<encrypt_input::Value>,
}
/// Nested message and enum types in `EncryptInput`.
pub mod encrypt_input {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(bool, tag = "1")]
        Ebool(bool),
        /// Canonical signed decimal strings; the SDK validates each type's range.
        #[prost(string, tag = "2")]
        EboolBigint(::prost::alloc::string::String),
        #[prost(string, tag = "3")]
        Euint8(::prost::alloc::string::String),
        #[prost(string, tag = "4")]
        Euint16(::prost::alloc::string::String),
        #[prost(string, tag = "5")]
        Euint32(::prost::alloc::string::String),
        #[prost(string, tag = "6")]
        Euint64(::prost::alloc::string::String),
        #[prost(string, tag = "7")]
        Euint128(::prost::alloc::string::String),
        #[prost(string, tag = "8")]
        Euint256(::prost::alloc::string::String),
        /// 20 bytes.
        #[prost(bytes, tag = "9")]
        Eaddress(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncryptRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<EncryptInput>,
    #[prost(bytes = "vec", tag = "3")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub user_address: ::prost::alloc::vec::Vec<u8>,
    /// SDK relayer timeout in whole milliseconds, independent of the gRPC deadline. Omit to keep the SDK default; zero is a zero-millisecond budget, not "no timeout".
    #[prost(uint32, optional, tag = "5")]
    pub timeout_ms: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptResponse {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub encrypted_values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "2")]
    pub input_proof: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareTransactionRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    /// Sender the SDK binds encrypted inputs to; it must match the key that signs.
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// Omission reads nonce, gas and fees from live chain state.
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<PrepareOptions>,
    #[prost(
        oneof = "prepare_transaction_request::Transaction",
        tags = "4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14"
    )]
    pub transaction: ::core::option::Option<prepare_transaction_request::Transaction>,
}
/// Nested message and enum types in `PrepareTransactionRequest`.
pub mod prepare_transaction_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Transaction {
        #[prost(message, tag = "4")]
        ConfidentialTransfer(super::ConfidentialTransfer),
        #[prost(message, tag = "5")]
        ConfidentialTransferFrom(super::ConfidentialTransferFrom),
        #[prost(message, tag = "6")]
        SetOperator(super::SetOperator),
        #[prost(message, tag = "7")]
        Unwrap(super::Unwrap),
        #[prost(message, tag = "8")]
        UnwrapAll(super::UnwrapAll),
        #[prost(message, tag = "9")]
        FinalizeUnwrap(super::FinalizeUnwrap),
        #[prost(message, tag = "10")]
        ApproveUnderlying(super::ApproveUnderlying),
        #[prost(message, tag = "11")]
        Wrap(super::Wrap),
        #[prost(message, tag = "12")]
        TransferAndCall(super::TransferAndCall),
        #[prost(message, tag = "13")]
        DelegateDecryption(super::DelegateDecryption),
        #[prost(message, tag = "14")]
        RevokeDelegation(super::RevokeDelegation),
    }
}
/// Each override has independent presence; amounts are canonical base-10 strings.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareOptions {
    #[prost(uint64, optional, tag = "1")]
    pub nonce: ::core::option::Option<u64>,
    #[prost(string, optional, tag = "2")]
    pub gas_limit: ::core::option::Option<::prost::alloc::string::String>,
    /// The fee pair is supplied together or not at all.
    #[prost(message, optional, tag = "3")]
    pub fees: ::core::option::Option<PrepareFees>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareFees {
    #[prost(string, tag = "1")]
    pub max_fee_per_gas: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub max_priority_fee_per_gas: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfidentialTransfer {
    #[prost(bytes = "vec", tag = "1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfidentialTransferFrom {
    #[prost(bytes = "vec", tag = "1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetOperator {
    #[prost(bytes = "vec", tag = "1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub operator: ::prost::alloc::vec::Vec<u8>,
    /// Required Unix timestamp in whole seconds; omission is rejected, never defaulted. A positive past value revokes.
    #[prost(uint64, optional, tag = "3")]
    pub until: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Unwrap {
    #[prost(bytes = "vec", tag = "1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnwrapAll {
    #[prost(bytes = "vec", tag = "1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalizeUnwrap {
    #[prost(bytes = "vec", tag = "1")]
    pub wrapper: ::prost::alloc::vec::Vec<u8>,
    /// unwrapRequestId or legacy encrypted amount from the UnwrapRequested log.
    #[prost(bytes = "vec", tag = "2")]
    pub unwrap_request_id_or_amount: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApproveUnderlying {
    #[prost(bytes = "vec", tag = "1")]
    pub underlying: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Wrap {
    #[prost(bytes = "vec", tag = "1")]
    pub wrapper: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransferAndCall {
    #[prost(bytes = "vec", tag = "1")]
    pub underlying: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub wrapper: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
    /// Omission self-shields to the sender; present empty bytes reach the SDK unchanged.
    #[prost(bytes = "vec", optional, tag = "4")]
    pub recipient_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Shared by PrepareTransaction and DelegateDecryption; offline-only fields belong on PrepareTransactionRequest.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DelegateDecryption {
    #[prost(bytes = "vec", tag = "1")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub delegate_address: ::prost::alloc::vec::Vec<u8>,
    /// Unix time in whole milliseconds; omission requests a permanent delegation.
    #[prost(uint64, optional, tag = "3")]
    pub expiration_date_ms: ::core::option::Option<u64>,
}
/// Shared by PrepareTransaction and RevokeDelegation; offline-only fields belong on PrepareTransactionRequest.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeDelegation {
    #[prost(bytes = "vec", tag = "1")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub delegate_address: ::prost::alloc::vec::Vec<u8>,
}
/// SDK output unchanged: no signature is produced and nothing is broadcast.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrepareTransactionResponse {
    #[prost(enumeration = "TransactionKind", tag = "1")]
    pub kind: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// RLP-encoded unsigned EIP-1559 transaction.
    #[prost(bytes = "vec", tag = "3")]
    pub unsigned_tx: ::prost::alloc::vec::Vec<u8>,
}
/// On-chain ACL delegation, distinct from the local delegation permits managed by the permit RPCs.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DelegateDecryptionRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, optional, tag = "2")]
    pub delegation: ::core::option::Option<DelegateDecryption>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeDelegationRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, optional, tag = "2")]
    pub delegation: ::core::option::Option<RevokeDelegation>,
}
/// Addresses contain exactly 20 bytes; the delegator is explicit because reads need no signer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DelegationQuery {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", tag = "2")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub delegate_address: ::prost::alloc::vec::Vec<u8>,
}
/// Mirrors the SDK TransactionResult: the broadcast hash and the mined receipt logs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionResult {
    #[prost(bytes = "vec", tag = "1")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "2")]
    pub logs: ::prost::alloc::vec::Vec<TransactionLog>,
}
/// Log emitter address is optional because provider adapters may omit it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransactionLog {
    #[prost(bytes = "vec", optional, tag = "1")]
    pub address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegateDecryptionResponse {
    #[prost(message, optional, tag = "1")]
    pub transaction: ::core::option::Option<TransactionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeDelegationResponse {
    #[prost(message, optional, tag = "1")]
    pub transaction: ::core::option::Option<TransactionResult>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IsDelegationActiveResponse {
    #[prost(bool, tag = "1")]
    pub is_active: bool,
}
/// Unix time in whole seconds as stored by the ACL: 0 means no delegation, 2^64-1 means permanent.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDelegationExpiryResponse {
    #[prost(uint64, tag = "1")]
    pub expiry_timestamp: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDelegationStatusResponse {
    #[prost(bool, tag = "1")]
    pub is_active: bool,
    #[prost(uint64, tag = "2")]
    pub expiry_timestamp: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StorageMethod {
    Unspecified = 0,
    Get = 1,
    Set = 2,
    Delete = 3,
}
impl StorageMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STORAGE_METHOD_UNSPECIFIED",
            Self::Get => "STORAGE_METHOD_GET",
            Self::Set => "STORAGE_METHOD_SET",
            Self::Delete => "STORAGE_METHOD_DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STORAGE_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "STORAGE_METHOD_GET" => Some(Self::Get),
            "STORAGE_METHOD_SET" => Some(Self::Set),
            "STORAGE_METHOD_DELETE" => Some(Self::Delete),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RelayerTransport {
    Unspecified = 0,
    Node = 1,
    Cleartext = 2,
}
impl RelayerTransport {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RELAYER_TRANSPORT_UNSPECIFIED",
            Self::Node => "RELAYER_TRANSPORT_NODE",
            Self::Cleartext => "RELAYER_TRANSPORT_CLEARTEXT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RELAYER_TRANSPORT_UNSPECIFIED" => Some(Self::Unspecified),
            "RELAYER_TRANSPORT_NODE" => Some(Self::Node),
            "RELAYER_TRANSPORT_CLEARTEXT" => Some(Self::Cleartext),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TransactionKind {
    Unspecified = 0,
    ConfidentialTransfer = 1,
    ConfidentialTransferFrom = 2,
    SetOperator = 3,
    Unwrap = 4,
    UnwrapAll = 5,
    FinalizeUnwrap = 6,
    ApproveUnderlying = 7,
    Wrap = 8,
    TransferAndCall = 9,
    DelegateDecryption = 10,
    RevokeDelegation = 11,
}
impl TransactionKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRANSACTION_KIND_UNSPECIFIED",
            Self::ConfidentialTransfer => "TRANSACTION_KIND_CONFIDENTIAL_TRANSFER",
            Self::ConfidentialTransferFrom => {
                "TRANSACTION_KIND_CONFIDENTIAL_TRANSFER_FROM"
            }
            Self::SetOperator => "TRANSACTION_KIND_SET_OPERATOR",
            Self::Unwrap => "TRANSACTION_KIND_UNWRAP",
            Self::UnwrapAll => "TRANSACTION_KIND_UNWRAP_ALL",
            Self::FinalizeUnwrap => "TRANSACTION_KIND_FINALIZE_UNWRAP",
            Self::ApproveUnderlying => "TRANSACTION_KIND_APPROVE_UNDERLYING",
            Self::Wrap => "TRANSACTION_KIND_WRAP",
            Self::TransferAndCall => "TRANSACTION_KIND_TRANSFER_AND_CALL",
            Self::DelegateDecryption => "TRANSACTION_KIND_DELEGATE_DECRYPTION",
            Self::RevokeDelegation => "TRANSACTION_KIND_REVOKE_DELEGATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSACTION_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "TRANSACTION_KIND_CONFIDENTIAL_TRANSFER" => Some(Self::ConfidentialTransfer),
            "TRANSACTION_KIND_CONFIDENTIAL_TRANSFER_FROM" => {
                Some(Self::ConfidentialTransferFrom)
            }
            "TRANSACTION_KIND_SET_OPERATOR" => Some(Self::SetOperator),
            "TRANSACTION_KIND_UNWRAP" => Some(Self::Unwrap),
            "TRANSACTION_KIND_UNWRAP_ALL" => Some(Self::UnwrapAll),
            "TRANSACTION_KIND_FINALIZE_UNWRAP" => Some(Self::FinalizeUnwrap),
            "TRANSACTION_KIND_APPROVE_UNDERLYING" => Some(Self::ApproveUnderlying),
            "TRANSACTION_KIND_WRAP" => Some(Self::Wrap),
            "TRANSACTION_KIND_TRANSFER_AND_CALL" => Some(Self::TransferAndCall),
            "TRANSACTION_KIND_DELEGATE_DECRYPTION" => Some(Self::DelegateDecryption),
            "TRANSACTION_KIND_REVOKE_DELEGATION" => Some(Self::RevokeDelegation),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod sidecar_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// SDK failures retain their code and retry information in gRPC trailers.
    /// Integer durations and counts are exact; omitted optional values use SDK defaults.
    #[derive(Debug, Clone)]
    pub struct SidecarServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SidecarServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SidecarServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SidecarServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SidecarServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Reports the version of @zama-fhe/sdk executing operations in this process.
        pub async fn get_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GetInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "GetInfo"));
            self.inner.unary(req, path, codec).await
        }
        /// Creates an independent SDK instance; no account or signer is required for public operations.
        pub async fn create_context(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateContextRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateContextResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/CreateContext",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "CreateContext"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Cancels active operations and disposes this context and its callback channels.
        pub async fn close_context(
            &mut self,
            request: impl tonic::IntoRequest<super::ContextRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseContextResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/CloseContext",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "CloseContext"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Cancels pending operations before changing the signer account; omission disconnects it.
        pub async fn update_account(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAccountRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateAccountResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/UpdateAccount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "UpdateAccount"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Attach once per context before signing. Actions may overlap; correlate both action and operation IDs.
        pub async fn signer_channel(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::SignerClientMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SignerServerMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/SignerChannel",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "SignerChannel"),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Attach once per context to serve application storage; keys and values remain opaque.
        pub async fn storage_channel(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::StorageClientMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StorageServerMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/StorageChannel",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "StorageChannel"),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Calls decryption.decryptValues, including automatic permit acquisition and credential recovery.
        pub async fn decrypt_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DecryptValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DecryptValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DecryptValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "DecryptValues"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls decryption.delegatedDecryptValues; an omitted account uses the delegator address.
        pub async fn delegated_decrypt_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegatedDecryptValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DelegatedDecryptValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DelegatedDecryptValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DelegatedDecryptValues",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls decryption.decryptPublicValues without requiring a signer.
        pub async fn decrypt_public_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DecryptPublicValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DecryptPublicValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DecryptPublicValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DecryptPublicValues",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls decryption.delegatedBatchDecryptValues; per-item failures remain results, fatal SDK errors fail the RPC.
        pub async fn delegated_batch_decrypt_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegatedBatchDecryptValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DelegatedBatchDecryptValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DelegatedBatchDecryptValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DelegatedBatchDecryptValues",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls offline.prepare; the caller signs and broadcasts the returned unsigned transaction.
        pub async fn prepare_transaction(
            &mut self,
            request: impl tonic::IntoRequest<super::PrepareTransactionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PrepareTransactionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/PrepareTransaction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "PrepareTransaction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls offline.preparePermit without signing; return the opaque envelope unchanged when registering.
        pub async fn prepare_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::PreparePermitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PreparePermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/PreparePermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "PreparePermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.registerPermit with the prepared envelope and signature.
        pub async fn register_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterPermitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RegisterPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "RegisterPermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.grantPermit; any wallet signing is requested on the signer channel.
        pub async fn grant_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::ContractsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GrantPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GrantPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "GrantPermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.grantDelegationPermit for the supplied delegator and contracts.
        pub async fn grant_delegation_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationContractsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GrantDelegationPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GrantDelegationPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "GrantDelegationPermit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.hasPermit using the SDK credential store and expiry rules.
        pub async fn has_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::ContractsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/HasPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "HasPermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.hasDelegationPermit for the supplied delegator and contracts.
        pub async fn has_delegation_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationContractsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasDelegationPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/HasDelegationPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "HasDelegationPermit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.revokePermits; omitted contracts and an empty list retain their distinct SDK meanings.
        pub async fn revoke_permits(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokePermitsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokePermitsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RevokePermits",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "RevokePermits"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.clear to clear locally stored permits.
        pub async fn clear_permits(
            &mut self,
            request: impl tonic::IntoRequest<super::OperationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClearPermitsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/ClearPermits",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "ClearPermits"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.warmTransportKeyPair; signing is requested only when the SDK requires it.
        pub async fn warm_transport_key_pair(
            &mut self,
            request: impl tonic::IntoRequest<super::OperationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WarmTransportKeyPairResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/WarmTransportKeyPair",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "WarmTransportKeyPair",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.warmTransportKeyPairScope for a shared credential scope.
        pub async fn warm_transport_key_pair_scope(
            &mut self,
            request: impl tonic::IntoRequest<super::ScopeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WarmTransportKeyPairScopeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/WarmTransportKeyPairScope",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "WarmTransportKeyPairScope",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls permits.revokeTransportKeyPair for the supplied credential scope.
        pub async fn revoke_transport_key_pair(
            &mut self,
            request: impl tonic::IntoRequest<super::ScopeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeTransportKeyPairResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RevokeTransportKeyPair",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "RevokeTransportKeyPair",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls sdk.encrypt; no wallet signing is required.
        pub async fn encrypt(
            &mut self,
            request: impl tonic::IntoRequest<super::EncryptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EncryptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/Encrypt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "Encrypt"));
            self.inner.unary(req, path, codec).await
        }
        /// Calls delegations.delegateDecryption; the delegator is the signer account and the write is requested on the signer channel.
        pub async fn delegate_decryption(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegateDecryptionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DelegateDecryptionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DelegateDecryption",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DelegateDecryption",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls delegations.revokeDelegation for the signer account's on-chain delegation.
        pub async fn revoke_delegation(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeDelegationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeDelegationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RevokeDelegation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "RevokeDelegation",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls delegations.isActive without requiring a signer.
        pub async fn is_delegation_active(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationQuery>,
        ) -> std::result::Result<
            tonic::Response<super::IsDelegationActiveResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/IsDelegationActive",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "IsDelegationActive",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls delegations.getExpiry without requiring a signer.
        pub async fn get_delegation_expiry(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationQuery>,
        ) -> std::result::Result<
            tonic::Response<super::GetDelegationExpiryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GetDelegationExpiry",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "GetDelegationExpiry",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Calls delegations.getStatus without requiring a signer.
        pub async fn get_delegation_status(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationQuery>,
        ) -> std::result::Result<
            tonic::Response<super::GetDelegationStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GetDelegationStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "GetDelegationStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
