// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInfoRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInfoResponse {
    #[prost(string, tag = "1")]
    pub sdk_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WalletAccount {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub chain_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateContextRequest {
    #[prost(string, tag = "1")]
    pub config_json: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub signer_enabled: bool,
    #[prost(message, optional, tag = "3")]
    pub account: ::core::option::Option<WalletAccount>,
    #[prost(message, optional, tag = "4")]
    pub storage: ::core::option::Option<StorageBinding>,
    #[prost(message, optional, tag = "5")]
    pub permit_storage: ::core::option::Option<StorageBinding>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateContextResponse {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContextRequest {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAccountRequest {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub account: ::core::option::Option<WalletAccount>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Operation {
    #[prost(string, tag = "1")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub operation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperationRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EncryptedInput {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearValue {
    #[prost(oneof = "clear_value::Value", tags = "1, 2, 3, 4, 5")]
    pub value: ::core::option::Option<clear_value::Value>,
}
/// Nested message and enum types in `ClearValue`.
pub mod clear_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        BigintValue(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "4")]
        UndefinedValue(bool),
        #[prost(double, tag = "5")]
        NumberValue(f64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearEntry {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<ClearValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<EncryptedInput>,
    #[prost(double, optional, tag = "3")]
    pub timeout_ms: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<ClearEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedDecryptValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<EncryptedInput>,
    #[prost(bytes = "vec", tag = "3")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub account_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, optional, tag = "5")]
    pub wait_for_propagation: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptPublicValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub encrypted_values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(double, optional, tag = "3")]
    pub timeout_ms: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecryptPublicValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<ClearEntry>,
    #[prost(bytes = "vec", tag = "2")]
    pub abi_encoded_clear_values: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub decryption_proof: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedBatchDecryptValuesRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<EncryptedInput>,
    #[prost(bytes = "vec", tag = "3")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub account_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(double, optional, tag = "5")]
    pub max_concurrency: ::core::option::Option<f64>,
    #[prost(bool, optional, tag = "6")]
    pub wait_for_propagation: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub retryable: bool,
    #[prost(double, optional, tag = "4")]
    pub retry_after_seconds: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchItem {
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub contract_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<ClearValue>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegatedBatchDecryptValuesResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<BatchItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreparePermitRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", tag = "2")]
    pub signer_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub contract_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub delegator_address: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(double, optional, tag = "5")]
    pub duration_days: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreparePermitResponse {
    #[prost(string, tag = "1")]
    pub prepared_permit_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPermitRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(string, tag = "2")]
    pub prepared_permit_json: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContractsRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub contract_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DelegationContractsRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(bytes = "vec", tag = "2")]
    pub delegator_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub contract_addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HasPermitResponse {
    #[prost(bool, tag = "1")]
    pub has_permit: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContractList {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokePermitsRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(message, optional, tag = "2")]
    pub contracts: ::core::option::Option<ContractList>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScopeRequest {
    #[prost(message, optional, tag = "1")]
    pub operation: ::core::option::Option<Operation>,
    #[prost(string, tag = "2")]
    pub scope_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignerReply {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignerClientMessage {
    #[prost(oneof = "signer_client_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<signer_client_message::Message>,
}
/// Nested message and enum types in `SignerClientMessage`.
pub mod signer_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attach(super::ContextRequest),
        #[prost(message, tag = "2")]
        Reply(super::SignerReply),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerAction {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub account: ::core::option::Option<WalletAccount>,
    #[prost(string, tag = "4")]
    pub typed_data_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignerReplyError {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignerActionCancelled {
    #[prost(string, tag = "1")]
    pub operation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignerServerMessage {
    #[prost(oneof = "signer_server_message::Message", tags = "1, 2, 3, 4")]
    pub message: ::core::option::Option<signer_server_message::Message>,
}
/// Nested message and enum types in `SignerServerMessage`.
pub mod signer_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attached(super::Empty),
        #[prost(message, tag = "2")]
        Action(super::SignerAction),
        #[prost(message, tag = "3")]
        ReplyError(super::SignerReplyError),
        #[prost(message, tag = "4")]
        Cancelled(super::SignerActionCancelled),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageBinding {
    #[prost(oneof = "storage_binding::Backend", tags = "1, 2, 3")]
    pub backend: ::core::option::Option<storage_binding::Backend>,
}
/// Nested message and enum types in `StorageBinding`.
pub mod storage_binding {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Backend {
        #[prost(message, tag = "1")]
        Memory(super::Empty),
        #[prost(string, tag = "2")]
        Persistent(::prost::alloc::string::String),
        #[prost(string, tag = "3")]
        Application(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageAction {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub backend_id: ::prost::alloc::string::String,
    #[prost(enumeration = "StorageMethod", tag = "3")]
    pub method: i32,
    #[prost(string, tag = "4")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageReply {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "3")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageClientMessage {
    #[prost(oneof = "storage_client_message::Message", tags = "1, 2")]
    pub message: ::core::option::Option<storage_client_message::Message>,
}
/// Nested message and enum types in `StorageClientMessage`.
pub mod storage_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attach(super::ContextRequest),
        #[prost(message, tag = "2")]
        Reply(super::StorageReply),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageReplyError {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub error: ::core::option::Option<SdkError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageServerMessage {
    #[prost(oneof = "storage_server_message::Message", tags = "1, 2, 3")]
    pub message: ::core::option::Option<storage_server_message::Message>,
}
/// Nested message and enum types in `StorageServerMessage`.
pub mod storage_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        Attached(super::Empty),
        #[prost(message, tag = "2")]
        Action(super::StorageAction),
        #[prost(message, tag = "3")]
        ReplyError(super::StorageReplyError),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StorageMethod {
    Unspecified = 0,
    Get = 1,
    Set = 2,
    Delete = 3,
}
impl StorageMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STORAGE_METHOD_UNSPECIFIED",
            Self::Get => "STORAGE_METHOD_GET",
            Self::Set => "STORAGE_METHOD_SET",
            Self::Delete => "STORAGE_METHOD_DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STORAGE_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "STORAGE_METHOD_GET" => Some(Self::Get),
            "STORAGE_METHOD_SET" => Some(Self::Set),
            "STORAGE_METHOD_DELETE" => Some(Self::Delete),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod sidecar_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SidecarServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SidecarServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SidecarServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SidecarServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SidecarServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GetInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "GetInfo"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_context(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateContextRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateContextResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/CreateContext",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "CreateContext"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn close_context(
            &mut self,
            request: impl tonic::IntoRequest<super::ContextRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/CloseContext",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "CloseContext"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_account(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateAccountRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/UpdateAccount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "UpdateAccount"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn signer_channel(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::SignerClientMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SignerServerMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/SignerChannel",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "SignerChannel"),
                );
            self.inner.streaming(req, path, codec).await
        }
        pub async fn storage_channel(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::StorageClientMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StorageServerMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/StorageChannel",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "StorageChannel"),
                );
            self.inner.streaming(req, path, codec).await
        }
        pub async fn decrypt_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DecryptValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DecryptValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DecryptValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "DecryptValues"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delegated_decrypt_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegatedDecryptValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DecryptValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DelegatedDecryptValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DelegatedDecryptValues",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn decrypt_public_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DecryptPublicValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DecryptPublicValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DecryptPublicValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DecryptPublicValues",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delegated_batch_decrypt_values(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegatedBatchDecryptValuesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DelegatedBatchDecryptValuesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/DelegatedBatchDecryptValues",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "DelegatedBatchDecryptValues",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn prepare_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::PreparePermitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PreparePermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/PreparePermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "PreparePermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn register_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterPermitRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RegisterPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "RegisterPermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn grant_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::ContractsRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GrantPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "GrantPermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn grant_delegation_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationContractsRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/GrantDelegationPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "GrantDelegationPermit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn has_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::ContractsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/HasPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "HasPermit"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn has_delegation_permit(
            &mut self,
            request: impl tonic::IntoRequest<super::DelegationContractsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HasPermitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/HasDelegationPermit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "HasDelegationPermit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn revoke_permits(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokePermitsRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RevokePermits",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "RevokePermits"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn clear_permits(
            &mut self,
            request: impl tonic::IntoRequest<super::OperationRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/ClearPermits",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zama.sdk.v1alpha1.SidecarService", "ClearPermits"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn warm_transport_key_pair(
            &mut self,
            request: impl tonic::IntoRequest<super::OperationRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/WarmTransportKeyPair",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "WarmTransportKeyPair",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn warm_transport_key_pair_scope(
            &mut self,
            request: impl tonic::IntoRequest<super::ScopeRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/WarmTransportKeyPairScope",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "WarmTransportKeyPairScope",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn revoke_transport_key_pair(
            &mut self,
            request: impl tonic::IntoRequest<super::ScopeRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zama.sdk.v1alpha1.SidecarService/RevokeTransportKeyPair",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zama.sdk.v1alpha1.SidecarService",
                        "RevokeTransportKeyPair",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
