/**
 * PROVISIONAL ABI — hand-transcribed from the `VaultBatcherConfidential` /
 * `DepositVaultBatcherConfidential` / `RedeemVaultBatcherConfidential`
 * contract interfaces, not generated from a compiled artifact.
 *
 * Every read function here (`vault`, `fromToken`, `toToken`, `currentBatchId`,
 * `batchState`, `totalDeposits`, `deposits`, `minBatchAge`, `callbackDeadline`,
 * `batchCreatedAt`, `batchDispatchedAt`) has been spot-checked against a live
 * deployed batcher on Sepolia and returns correctly; `join` has too, via an
 * actual submitted transaction. The remaining write functions (`claim`,
 * `quit`, `recover`, `dispatchBatch`) are structurally identical to `join`
 * but individually unverified — checking those requires actually reaching
 * their preconditions on-chain (a finalized/cancelable batch).
 *
 * `packages/sdk`'s ABIs are generated by `pnpm abi:build` from
 * `contracts/out/*.json` (see `docs/agents/architecture.md` and
 * `turbo.json`'s `//#abi:build` task) — this file should be regenerated the
 * same way once the vault contracts are vendored into this repo.
 */
export const vaultBatcherAbi = [
  {
    type: "function",
    name: "join",
    inputs: [
      { name: "beneficiary", type: "address", internalType: "address" },
      { name: "encryptedAmount", type: "bytes32", internalType: "externalEuint64" },
      { name: "inputProof", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "quit",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recover",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchBatch",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "currentBatchId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchState",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalDeposits",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deposits",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vault",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fromToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC7984ERC20Wrapper" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "toToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC7984ERC20Wrapper" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minBatchAge",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "callbackDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchCreatedAt",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchDispatchedAt",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
] as const;
