/**
 * ABI for the deposit and redeem vault batchers, which share one interface.
 * Owner-only writes and the relayer-driven `dispatchBatchCallback` are omitted;
 * every custom error is kept so reverts decode to a name.
 */
export const vaultBatcherAbi = [
  {
    type: "function",
    name: "batchCallbackDeadline",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchCreatedAt",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchDispatchedAt",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchMaxSlippageBps",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchMinBatchAge",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchState",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum BatcherConfidential.BatchState" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "callbackDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "currentBatchId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deposits",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dispatchBatch",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "exchangeRate",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "exchangeRateDecimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "fromToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC7984ERC20Wrapper" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "join",
    inputs: [
      { name: "beneficiary", type: "address", internalType: "address" },
      { name: "encryptedAmount", type: "bytes32", internalType: "externalEuint64" },
      { name: "inputProof", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "joined", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "maxSlippageBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minBatchAge",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quit",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recover",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "refunded", type: "bytes32", internalType: "euint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "toToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC7984ERC20Wrapper" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalDeposits",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unwrapRequestId",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vault",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC4626" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "BatchCanceled",
    inputs: [{ name: "batchId", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "BatchDispatched",
    inputs: [{ name: "batchId", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "BatchFinalized",
    inputs: [
      { name: "batchId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "exchangeRate", type: "uint64", indexed: false, internalType: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "batchId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "bytes32", indexed: false, internalType: "euint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Joined",
    inputs: [
      { name: "batchId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "bytes32", indexed: false, internalType: "euint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Quit",
    inputs: [
      { name: "batchId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "bytes32", indexed: false, internalType: "euint64" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "BatchNonexistent",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "BatchTooYoung",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "elapsed", type: "uint256", internalType: "uint256" },
      { name: "required", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "BatchUnexpectedState",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "current", type: "uint8", internalType: "enum BatcherConfidential.BatchState" },
      { name: "expectedStates", type: "bytes32", internalType: "bytes32" },
    ],
  },
  { type: "error", name: "DuplicateUnderlyingTokens", inputs: [] },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  {
    type: "error",
    name: "IntermediateStepToTokenBalanceChanged",
    inputs: [{ name: "batchId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "InvalidBeneficiary", inputs: [] },
  { type: "error", name: "InvalidCallbackDeadline", inputs: [] },
  {
    type: "error",
    name: "InvalidExchangeRate",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "totalDeposits", type: "uint256", internalType: "uint256" },
      { name: "exchangeRate", type: "uint64", internalType: "uint64" },
    ],
  },
  { type: "error", name: "InvalidKMSSignatures", inputs: [] },
  { type: "error", name: "InvalidMaxSlippageBps", inputs: [] },
  { type: "error", name: "InvalidMinBatchAge", inputs: [] },
  { type: "error", name: "InvalidTokenRate", inputs: [] },
  {
    type: "error",
    name: "InvalidWrapperToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "RouteAssetMismatch",
    inputs: [
      { name: "actualAsset", type: "address", internalType: "address" },
      { name: "expectedAsset", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "RouteShareMismatch",
    inputs: [
      { name: "actualShare", type: "address", internalType: "address" },
      { name: "expectedShare", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "SafeCastOverflowedUintDowncast",
    inputs: [
      { name: "bits", type: "uint8", internalType: "uint8" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "SenderNotAllowedToUseHandle",
    inputs: [
      { name: "handle", type: "bytes32", internalType: "bytes32" },
      { name: "sender", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "SlippageExceeded",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "actual", type: "uint256", internalType: "uint256" },
      { name: "minimum", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "ZamaProtocolUnsupported", inputs: [] },
  {
    type: "error",
    name: "ZeroDeposits",
    inputs: [
      { name: "batchId", type: "uint256", internalType: "uint256" },
      { name: "account", type: "address", internalType: "address" },
    ],
  },
] as const;
