id: rename-config-session-storage
snapshots:
  'createConfig({ storage, sessionStorage: sessionDBStorage });':
    fixed: 'createConfig({ storage, permitStorage: sessionDBStorage });'
    labels:
    - source: 'sessionStorage: sessionDBStorage'
      style: primary
      start: 24
      end: 56
    - source: 'createConfig({ storage, sessionStorage: sessionDBStorage })'
      style: secondary
      start: 0
      end: 59
    - source: '({ storage, sessionStorage: sessionDBStorage })'
      style: secondary
      start: 12
      end: 59
    - source: '{ storage, sessionStorage: sessionDBStorage }'
      style: secondary
      start: 13
      end: 58
  'createZamaConfig({ sessionStorage: sessionDBStorage, storage });':
    fixed: 'createZamaConfig({ permitStorage: sessionDBStorage, storage });'
    labels:
    - source: 'sessionStorage: sessionDBStorage'
      style: primary
      start: 19
      end: 51
    - source: 'createZamaConfig({ sessionStorage: sessionDBStorage, storage })'
      style: secondary
      start: 0
      end: 63
    - source: '({ sessionStorage: sessionDBStorage, storage })'
      style: secondary
      start: 16
      end: 63
    - source: '{ sessionStorage: sessionDBStorage, storage }'
      style: secondary
      start: 17
      end: 62
