import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  approvedExamples,
  buildCorpusManifest,
  loadGitbookSource,
  normalizeGitbookMarkdown,
  rawGithubUrl,
  repoRoot,
} from "./lib/corpus.mjs";

const generatedNotice = "<!-- DO NOT EDIT: generated by `pnpm llm:build`. -->";

function normalizeInlineMarkdown(content) {
  return content
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[*_`]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function loadSdkDescription() {
  const readme = readFileSync(join(repoRoot, "README.md"), "utf8");
  const section = readme.match(/### What is Zama SDK\?\n\n([\s\S]*?)(?:\n\n|$)/u);
  if (!section) {
    throw new Error("Could not find README 'What is Zama SDK?' description.");
  }
  return normalizeInlineMarkdown(section[1]);
}

function formatIndexSection(title, entries) {
  const lines = [`## ${title}`, ""];
  for (const entry of entries) {
    lines.push(
      `- [${entry.title}](${entry.source_url ?? rawGithubUrl(entry.source_path)}): ${entry.description}`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function formatGroupedDocsSection(entries) {
  const sections = [
    { title: "Introduction", categories: ["introduction"] },
    { title: "Getting Started", categories: ["tutorials"] },
    { title: "Guides", categories: ["guides"] },
    { title: "SDK Reference", categories: ["reference-sdk"] },
    { title: "React Reference", categories: ["reference-react"] },
    { title: "Concepts", categories: ["concepts"] },
  ];

  const lines = ["## Official Documentation", ""];
  for (const section of sections) {
    const group = entries.filter((entry) => section.categories.includes(entry.category));
    if (group.length === 0) {
      continue;
    }
    lines.push(`### ${section.title}`, "");
    for (const entry of group) {
      lines.push(
        `- [${entry.title}](${entry.source_url ?? rawGithubUrl(entry.source_path)}): ${entry.description}`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function buildLlmsTxt(manifest) {
  const sdkDescription = loadSdkDescription();
  const docs = manifest.entries.filter(
    (entry) => entry.source_type === "official-doc" && entry.include_in_llms_txt,
  );
  const examples = manifest.entries.filter(
    (entry) => entry.source_type === "official-example" && entry.include_in_llms_txt,
  );
  const readmes = manifest.entries.filter(
    (entry) => entry.source_type === "package-readme" && entry.include_in_llms_txt,
  );

  return [
    "# Zama SDK",
    "",
    `> ${sdkDescription}`,
    "",
    generatedNotice,
    "",
    "This file is usable without cloning the SDK repository. Links point to raw GitHub Markdown sources.",
    "",
    "Source of truth: official documentation, approved official examples, and package READMEs. API reports are fallback reference material and are intentionally excluded from this index.",
    "",
    "Use this file for discovery. Follow the links to fetch the smallest source that answers the task. Start with the official docs, then move to the approved examples that match the target stack.",
    "",
    formatGroupedDocsSection(docs).trimEnd(),
    "",
    formatIndexSection("Official Examples", examples).trimEnd(),
    "",
    formatIndexSection("Package READMEs", readmes).trimEnd(),
  ].join("\n");
}

export function buildEntryBlock(entry, content) {
  return [
    `## ${entry.title}`,
    "",
    `- source_type: ${entry.source_type}`,
    `- source_path: ${entry.source_path}`,
    `- source_url: ${entry.source_url ?? rawGithubUrl(entry.source_path)}`,
    `- logical_path: ${entry.logical_path}`,
    "",
    content.trim(),
    "",
  ].join("\n");
}

export function buildLlmsFull(manifest) {
  const sdkDescription = loadSdkDescription();
  const docs = manifest.entries.filter(
    (entry) => entry.source_type === "official-doc" && entry.include_in_llms_full,
  );
  const examples = manifest.entries.filter(
    (entry) => entry.source_type === "official-example" && entry.include_in_llms_full,
  );
  const readmes = manifest.entries.filter(
    (entry) => entry.source_type === "package-readme" && entry.include_in_llms_full,
  );

  const sections = [
    "# Zama SDK",
    "",
    `> ${sdkDescription}`,
    "",
    generatedNotice,
    "",
    "Use `llms.txt` for discovery when you do not need the full corpus.",
    "",
    "This file is usable without cloning the SDK repository. `source_path` entries are repository-relative provenance paths; `source_url` entries are fetchable raw GitHub sources.",
    "",
    "Source of truth:",
    "",
    "1. Official documentation published through GitBook and sourced from `docs/gitbook/src`",
    "2. Approved official examples",
    "3. Package READMEs for onboarding context",
    "",
    "API reports are intentionally excluded from this file. They remain available in the repository as fallback reference material.",
    "",
    "## Official Documentation",
    "",
  ];

  for (const entry of docs) {
    sections.push(
      buildEntryBlock(
        entry,
        normalizeGitbookMarkdown(entry.source_path, loadGitbookSource(entry.source_path)),
      ),
    );
  }

  sections.push("## Official Examples", "");
  for (const entry of examples) {
    const content = readFileSync(join(repoRoot, entry.source_path), "utf8").trim();
    sections.push(buildEntryBlock(entry, content));
  }

  sections.push("## Package READMEs", "");
  for (const entry of readmes) {
    const content = readFileSync(join(repoRoot, entry.source_path), "utf8").trim();
    sections.push(buildEntryBlock(entry, content));
  }

  return sections.join("\n");
}

export function cleanGeneratedMarkdown(content) {
  return `${content
    .split("\n")
    .map((line) => line.trimEnd())
    .join("\n")
    .replace(/\n+$/u, "")}\n`;
}

function formatManifest(manifestPath) {
  const result = spawnSync("oxfmt", [manifestPath], { stdio: "inherit" });
  if (result.status !== 0) {
    throw new Error(`Failed to format ${manifestPath}`);
  }
}

export function writeLlmsArtifacts(manifest = buildCorpusManifest()) {
  const manifestDir = join(repoRoot, "docs/llm");
  const manifestPath = join(manifestDir, "corpus-manifest.json");
  mkdirSync(manifestDir, { recursive: true });
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  formatManifest(manifestPath);
  writeFileSync(join(repoRoot, "llms.txt"), cleanGeneratedMarkdown(buildLlmsTxt(manifest)));
  writeFileSync(join(repoRoot, "llms-full.txt"), cleanGeneratedMarkdown(buildLlmsFull(manifest)));
  console.log(
    `Wrote docs/llm/corpus-manifest.json, llms.txt, and llms-full.txt for ${approvedExamples.length} approved examples.`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeLlmsArtifacts();
}
