[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.27"
evm_version = "cancun"
optimizer = true
optimizer_runs = 100

fs_permissions = [{ access = "read-write", path = "./" }]

[profile.default.fmt]
line_length = 120

[dependencies]
"protocol-apps-wrapper" = { version = "da4afe387420", git = "https://github.com/zama-ai/protocol-apps", rev = "da4afe387420" }
"protocol-apps-registry" = { version = "f51845b08cc2", git = "https://github.com/zama-ai/protocol-apps", rev = "f51845b08cc2" }
