// DO NOT EDIT: generated by `pnpm abi:build` from
// contracts/out/IERC165.sol/IERC165.json.
// Regenerate after `pnpm contracts:build`; `pnpm abi:check` enforces this in CI.
export const erc165Abi = [
  {
    type: "function",
    name: "supportsInterface",
    inputs: [
      {
        name: "interfaceId",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
] as const;
