// Manually transcribed — NOT generated by `pnpm abi:build`, unlike this file's
// siblings. `KMSGeneration` isn't wired into this repo's Forge build: it lives
// in the `fhevm` submodule (contracts/lib/fhevm), which has no remapping in
// contracts/remappings.txt (only `forge-fhevm`, the mock/testing lib, does).
// Wiring it in is a separate follow-up, once a real deployment exists to
// compile/verify against.
//
// Source: contracts/lib/fhevm/host-contracts/contracts/interfaces/IKMSGeneration.sol
// at submodule commit 0c30b139d7f4b1c76072889cbc11c2f3d642b63a (tag v0.14.0-0+12).
// Only the two read functions this SDK needs; the full interface also has
// keygen/crsgen requests, responses, and lifecycle queries this SDK never calls.
export const kmsGenerationAbi = [
  {
    type: "function",
    name: "getKeyMaterials",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "string[]", internalType: "string[]" },
      {
        name: "",
        type: "tuple[]",
        internalType: "struct IKMSGeneration.KeyDigest[]",
        components: [
          { name: "keyType", type: "uint8", internalType: "enum IKMSGeneration.KeyType" },
          { name: "digest", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCrsMaterials",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "string[]", internalType: "string[]" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
] as const;
