// DO NOT EDIT: generated by `pnpm abi:build` from
// contracts/out/IKMSGeneration.sol/IKMSGeneration.json.
// Regenerate after `pnpm contracts:build`; `pnpm abi:check` enforces this in CI.
export const kmsGenerationAbi = [
  {
    type: "function",
    name: "abortCrsgen",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "abortKeygen",
    inputs: [{ name: "prepKeygenId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "crsgenRequest",
    inputs: [
      { name: "maxBitLength", type: "uint256", internalType: "uint256" },
      { name: "paramsType", type: "uint8", internalType: "enum IKMSGeneration.ParamsType" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "crsgenResponse",
    inputs: [
      { name: "crsId", type: "uint256", internalType: "uint256" },
      { name: "crsDigest", type: "bytes", internalType: "bytes" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getActiveCrsId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveKeyId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCompletedCrsIds",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCompletedKeyIds",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getConsensusTxSenders",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCrsCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCrsMaterials",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "string[]", internalType: "string[]" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCrsParamsType",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum IKMSGeneration.ParamsType" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getKeyCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getKeyInfo",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct IKMSGeneration.KeyInfo",
        components: [
          { name: "prepKeygenId", type: "uint256", internalType: "uint256" },
          { name: "keyId", type: "uint256", internalType: "uint256" },
          { name: "paramsType", type: "uint8", internalType: "enum IKMSGeneration.ParamsType" },
          {
            name: "keyDigests",
            type: "tuple[]",
            internalType: "struct IKMSGeneration.KeyDigest[]",
            components: [
              { name: "keyType", type: "uint8", internalType: "enum IKMSGeneration.KeyType" },
              { name: "digest", type: "bytes", internalType: "bytes" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getKeyMaterials",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "string[]", internalType: "string[]" },
      {
        name: "",
        type: "tuple[]",
        internalType: "struct IKMSGeneration.KeyDigest[]",
        components: [
          { name: "keyType", type: "uint8", internalType: "enum IKMSGeneration.KeyType" },
          { name: "digest", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getKeyParamsType",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum IKMSGeneration.ParamsType" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVersion",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "isRequestDone",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "keygen",
    inputs: [{ name: "paramsType", type: "uint8", internalType: "enum IKMSGeneration.ParamsType" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "keygenResponse",
    inputs: [
      { name: "keyId", type: "uint256", internalType: "uint256" },
      {
        name: "keyDigests",
        type: "tuple[]",
        internalType: "struct IKMSGeneration.KeyDigest[]",
        components: [
          { name: "keyType", type: "uint8", internalType: "enum IKMSGeneration.KeyType" },
          { name: "digest", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "prepKeygenResponse",
    inputs: [
      { name: "prepKeygenId", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AbortCrsgen",
    inputs: [{ name: "crsId", type: "uint256", indexed: false, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "AbortKeygen",
    inputs: [{ name: "prepKeygenId", type: "uint256", indexed: false, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "ActivateCrs",
    inputs: [
      { name: "crsId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "kmsNodeStorageUrls", type: "string[]", indexed: false, internalType: "string[]" },
      { name: "crsDigest", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ActivateKey",
    inputs: [
      { name: "keyId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "kmsNodeStorageUrls", type: "string[]", indexed: false, internalType: "string[]" },
      {
        name: "keyDigests",
        type: "tuple[]",
        indexed: false,
        internalType: "struct IKMSGeneration.KeyDigest[]",
        components: [
          { name: "keyType", type: "uint8", internalType: "enum IKMSGeneration.KeyType" },
          { name: "digest", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CrsgenRequest",
    inputs: [
      { name: "crsId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "maxBitLength", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "paramsType",
        type: "uint8",
        indexed: false,
        internalType: "enum IKMSGeneration.ParamsType",
      },
      { name: "extraData", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CrsgenResponse",
    inputs: [
      { name: "crsId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "crsDigest", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "signature", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "kmsTxSender", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "KeygenRequest",
    inputs: [
      { name: "prepKeygenId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "keyId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "extraData", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "KeygenResponse",
    inputs: [
      { name: "keyId", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "keyDigests",
        type: "tuple[]",
        indexed: false,
        internalType: "struct IKMSGeneration.KeyDigest[]",
        components: [
          { name: "keyType", type: "uint8", internalType: "enum IKMSGeneration.KeyType" },
          { name: "digest", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "signature", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "kmsTxSender", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PrepKeygenRequest",
    inputs: [
      { name: "prepKeygenId", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "paramsType",
        type: "uint8",
        indexed: false,
        internalType: "enum IKMSGeneration.ParamsType",
      },
      { name: "extraData", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PrepKeygenResponse",
    inputs: [
      { name: "prepKeygenId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "signature", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "kmsTxSender", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AbortCrsgenAlreadyDone",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "AbortCrsgenInvalidId",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "AbortKeygenAlreadyDone",
    inputs: [{ name: "prepKeygenId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "AbortKeygenInvalidId",
    inputs: [{ name: "prepKeygenId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CrsAborted",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CrsNotGenerated",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CrsgenNotRequested",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CrsgenOngoing",
    inputs: [{ name: "crsId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "DeserializingExtraDataFail", inputs: [] },
  {
    type: "error",
    name: "EmptyKeyDigests",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "KeyAborted",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "KeyManagementRequestPending", inputs: [] },
  {
    type: "error",
    name: "KeyNotGenerated",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "KeygenNotRequested",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "KeygenOngoing",
    inputs: [{ name: "keyId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "KmsAlreadySignedForCrsgen",
    inputs: [
      { name: "crsId", type: "uint256", internalType: "uint256" },
      { name: "kmsSigner", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "KmsAlreadySignedForKeygen",
    inputs: [
      { name: "keyId", type: "uint256", internalType: "uint256" },
      { name: "kmsSigner", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "KmsAlreadySignedForPrepKeygen",
    inputs: [
      { name: "prepKeygenId", type: "uint256", internalType: "uint256" },
      { name: "kmsSigner", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "KmsSignerDoesNotMatchTxSender",
    inputs: [
      { name: "signerAddress", type: "address", internalType: "address" },
      { name: "txSenderAddress", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "NotKmsSigner",
    inputs: [{ name: "signerAddress", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "NotKmsTxSender",
    inputs: [{ name: "txSenderAddress", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "PrepKeygenNotRequested",
    inputs: [{ name: "prepKeygenId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "UnsupportedExtraDataVersion",
    inputs: [{ name: "version", type: "uint8", internalType: "uint8" }],
  },
] as const;
