import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

// Each entry maps a Forge artifact to one SDK ABI file. `encryptedAbi` and
// `wrapperAbi` are kept as two exports purely for SDK-internal import
// compatibility — both surfaces are sliced from the deployed
// ConfidentialWrapperV3 contract, so they share the full ABI verbatim.
export const targets = [
  {
    artifactRelPath: "contracts/out/ConfidentialWrapperV3.sol/ConfidentialWrapperV3.json",
    path: "packages/sdk/src/abi/encrypted.abi.ts",
    exportName: "encryptedAbi",
  },
  {
    artifactRelPath: "contracts/out/ConfidentialWrapperV3.sol/ConfidentialWrapperV3.json",
    path: "packages/sdk/src/abi/wrapper.abi.ts",
    exportName: "wrapperAbi",
  },
  {
    artifactRelPath: "contracts/out/Impl.sol/IACL.json",
    path: "packages/sdk/src/abi/acl.abi.ts",
    exportName: "aclAbi",
  },
];

export function headerFor(artifactRelPath) {
  return `// DO NOT EDIT: generated by \`pnpm abi:build\` from
// ${artifactRelPath}.
// Regenerate after \`pnpm contracts:build\`; \`pnpm abi:check\` enforces this in CI.
`;
}

export function loadAbi(artifactRelPath) {
  const artifactPath = join(repoRoot, artifactRelPath);
  let raw;
  try {
    raw = readFileSync(artifactPath, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") {
      throw new Error(
        `Compiled artifact not found: ${artifactPath}\nRun \`pnpm contracts:build\` first.`,
        { cause: err },
      );
    }
    throw err;
  }
  const json = JSON.parse(raw);
  if (!Array.isArray(json.abi)) {
    throw new TypeError(`Artifact has no .abi array: ${artifactPath}`);
  }
  return json.abi;
}

export function buildAbiSource(exportName, abi, artifactRelPath) {
  return `${headerFor(artifactRelPath)}export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

function format(paths) {
  const result = spawnSync("oxfmt", paths, { stdio: "inherit", cwd: repoRoot });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

export function writeAbiArtifacts() {
  const written = [];
  for (const target of targets) {
    const abi = loadAbi(target.artifactRelPath);
    const fullPath = join(repoRoot, target.path);
    writeFileSync(fullPath, buildAbiSource(target.exportName, abi, target.artifactRelPath));
    written.push(fullPath);
  }
  format(written);
  console.log(`Wrote ${written.length} ABI files:`);
  for (const target of targets) {
    console.log(`  - ${target.path} (from ${target.artifactRelPath})`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    writeAbiArtifacts();
  } catch (err) {
    console.error(err.message ?? err);
    process.exit(1);
  }
}
