import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

export const artifactRelPath = "contracts/out/ConfidentialWrapperV3.sol/ConfidentialWrapperV3.json";

export const artifactPath = join(repoRoot, artifactRelPath);

// encryptedAbi and wrapperAbi are kept as two exports purely for SDK-internal
// import compatibility. Both surfaces are sliced from the deployed
// ConfidentialWrapperV3 contract, so they share the full ABI verbatim.
export const targets = [
  { path: "packages/sdk/src/abi/encrypted.abi.ts", exportName: "encryptedAbi" },
  { path: "packages/sdk/src/abi/wrapper.abi.ts", exportName: "wrapperAbi" },
];

export const header = `// DO NOT EDIT: generated by \`pnpm abi:build\` from
// ${artifactRelPath}.
// Regenerate after \`pnpm contracts:build\`; \`pnpm abi:check\` enforces this in CI.
`;

export function loadAbi() {
  let raw;
  try {
    raw = readFileSync(artifactPath, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") {
      throw new Error(
        `Compiled artifact not found: ${artifactPath}\nRun \`pnpm contracts:build\` first.`,
        { cause: err },
      );
    }
    throw err;
  }
  const json = JSON.parse(raw);
  if (!Array.isArray(json.abi)) {
    throw new TypeError(`Artifact has no .abi array: ${artifactPath}`);
  }
  return json.abi;
}

export function buildAbiSource(exportName, abi) {
  return `${header}export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

function format(paths) {
  const result = spawnSync("oxfmt", paths, { stdio: "inherit", cwd: repoRoot });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

export function writeAbiArtifacts() {
  const abi = loadAbi();
  const written = [];
  for (const target of targets) {
    const fullPath = join(repoRoot, target.path);
    writeFileSync(fullPath, buildAbiSource(target.exportName, abi));
    written.push(fullPath);
  }
  format(written);
  console.log(`Wrote ${written.length} ABI files from ${artifactRelPath}:`);
  for (const target of targets) {
    console.log(`  - ${target.path}`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    writeAbiArtifacts();
  } catch (err) {
    console.error(err.message ?? err);
    process.exit(1);
  }
}
