[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
test = "test"
solc = "0.8.27"
evm_version = "cancun"
allow_paths = ["../../.."]

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
forge-std = "1.14.0"
